### ISSUE TITLE
请问调试php的时候，有错误时页面只显示“PHP Throw Exception”，怎样查看具体错误？

### ISSUE THREAD

**Issue by javacty** [webcpp/hi-nginx-demo#1]
nginx的日志里也没有

**Comment by webcpp** [comment]
tail -n10 /usr/local/nginx/logs/error.log

**Comment by javacty** [comment]
nginx配置:
location / {
            hi_php_script php/index.php;
}
===========================
php代码，比如少；之类的语法错误：
页面显示：404 Not Found
nginx log：PHP Warning:  Unknown: class '\hi\request' is undefined. in Unknown on line 0

请问可不可以直接显示php原本的报错信息？
另外，每次修改php代码，要重启nginx，有没有配置开发模式的方法，不用重启nginx？
